name: 'stream'
version: '3.8'
services:
    kafka:
        image: confluentinc/cp-kafka:7.5.1
        hostname: kafka
        container_name: kafka
        ports:
            - '9092:9092' # Internal listener
            - '9093:9093' # Controller listener
            - '29092:29092' # External listener
        environment:
            KAFKA_KRAFT_MODE: 'true'
            KAFKA_PROCESS_ROLES: controller,broker
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
            KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_EXTERNAL://0.0.0.0:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:29092
            KAFKA_LOG_DIRS: /var/lib/kafka/data
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG_RETENTION_HOURS: 168
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            CLUSTER_ID: 'MkU3OEVZQlNEMzRmY3dOVA=='
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/var/lib/kafka/data
        networks:
            - kafka-net
    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        depends_on:
            - kafka
        ports:
            - 9000:9000
        environment:
            KAFKA_BROKER_CONNECT: kafka:9092
        networks:
            - kafka-net

networks:
    kafka-net:
